# Series in pandas
   - its a one dimension labelled array

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([10,20,30,40,50,60])
print(s1)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [3]:
s1 = pd.Series([10,20,30,40,50,60], index=['a','b','c','d','e','f'])
print(s1)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [4]:
s2 = pd.Series([10,20,30,40,50,60], index=['a','b','c','d','e','f'], name='scores')
print(s2)

a    10
b    20
c    30
d    40
e    50
f    60
Name: scores, dtype: int64

In [5]:
# create series from dict

data = {'a':10,'b':20,'c':30,'d':40}
pd.Series(data)

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
import numpy as np

In [7]:
np_array = np.array([10,20,30,40,50,60])
s4 = pd.Series(np_array)
print(s4)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [8]:
data = {'a':10,'b':2.220,'c':"30",'d':True}
pd.Series(data)

a      10
b    2.22
c      30
d    True
dtype: object

# Series indexing and slicing

In [9]:
data = {'a':10,'b':20,'c':30,'d':40}
s7 = pd.Series(data, name='scores')
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: int64

In [10]:
print(s7.values[0])
print(s7.values[1])        # This are Positional Index.
print(s7.values[2])

10
20
30

In [11]:
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: int64

In [12]:
# Native index

print(s7.loc['a'])

10

In [13]:
print(s7.loc[['a','b']])

a    10
b    20
Name: scores, dtype: int64

In [14]:
# Positional Index

print(s7.iloc[0])

10

In [15]:
print(s7.iloc[[0,1,2]])

a    10
b    20
c    30
Name: scores, dtype: int64

In [16]:
print(s7.iloc[0:3])

a    10
b    20
c    30
Name: scores, dtype: int64

In [17]:
# Both are print the same value but in fires we use variable name and second one we use index.

In [18]:
data = {'a':10,'b':20,'c':30,'d':40, 0 : 100, 1 : 101, 2 : 400, 6 : 700}
s8 = pd.Series(data, name='scores')
print(s8)

a     10
b     20
c     30
d     40
0    100
1    101
2    400
6    700
Name: scores, dtype: int64

In [19]:
s8.loc[0:2]   # it does't print from 'a'. it started from '0'.

0    100
1    101
2    400
Name: scores, dtype: int64

In [20]:
# Slicing
# - loc [start, end] : end is inclusive.
# - iloc [start, end] : end is exclusive.

# dataframe

In [21]:
data = {
    'Name' : ['Fardin','Nadim','Sahid'],
    'Age' : [24,26,28],
    'city' :['baruan','baranga','']
}

In [22]:
df = pd.DataFrame(data)
print(df)

     Name  Age     city
0  Fardin   24   baruan
1   Nadim   26  baranga
2   Sahid   28

In [23]:
arr_data = np.array([[1,2],[3,4],[5,6]])

In [24]:
df_2 = pd.DataFrame(arr_data)

In [25]:
d2 = pd.DataFrame(arr_data,columns=['A','B'])
print(d2)

   A  B
0  1  2
1  3  4
2  5  6

# Accessing the values

In [26]:
data = {
    'Name' : ['Fardin','Nadim','Sahid'],
    'Age' : [24,26,28],
    'city' :['baruan','baranga','']
}

In [27]:
df_4 = pd.DataFrame(data)

In [28]:
type(df_4)

pandas.core.frame.DataFrame

In [29]:
print(df_4)

     Name  Age     city
0  Fardin   24   baruan
1   Nadim   26  baranga
2   Sahid   28

In [30]:
print(df_4['Name'])

0    Fardin
1     Nadim
2     Sahid
Name: Name, dtype: object

In [31]:
print(df_4['city'])

0     baruan
1    baranga
2
Name: city, dtype: object

In [32]:
print(df_4['Name'])
print('+'*50)

print(df_4[['Name','Age']])
print('*'*50)

print(df_4[['Name','Age','city']])
print('%'*50)

print(df.loc[0:2]) # Inclusive means it return all mention index like "0,1 and 2"
print('#'*50)

print(df.iloc[0:2]) # Exclusive meand it return "0 and 1" index, it return (n-1) form.

0    Fardin
1     Nadim
2     Sahid
Name: Name, dtype: object
++++++++++++++++++++++++++++++++++++++++++++++++++
     Name  Age
0  Fardin   24
1   Nadim   26
2   Sahid   28
**************************************************
     Name  Age     city
0  Fardin   24   baruan
1   Nadim   26  baranga
2   Sahid   28
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Name  Age     city
0  Fardin   24   baruan
1   Nadim   26  baranga
2   Sahid   28
##################################################
     Name  Age     city
0  Fardin   24   baruan
1   Nadim   26  baranga

# Working with real Data

In [33]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [34]:
df = pd.read_csv(titanic_dataset_github_url) # raw data

In [35]:
# preview of the dataframe

# 1st 5 rows

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
# last 5 rows

df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [37]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [38]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [39]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [40]:
df[['Name','Age','Survived']]

                                                  Name   Age  Survived
0                              Braund, Mr. Owen Harris  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                             Allen, Mr. William Henry  35.0         0
..                                                 ...   ...       ...
886                              Montvila, Rev. Juozas  27.0         0
887                       Graham, Miss. Margaret Edith  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN         0
889                              Behr, Mr. Karl Howell  26.0         1
890                                Dooley, Mr. Patrick  32.0         0

[891 rows x 3 columns]

In [41]:
df.loc[0] # first row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [42]:
df.loc[0,'Name'] # name of the passenger at index 0.

'Braund, Mr. Owen Harris'

In [43]:
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [44]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [45]:
df.iloc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [46]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
df.iloc[0,3] # Position index

'Braund, Mr. Owen Harris'

# Conditional selection

In [48]:
# get all the rows where persion age is greater then 70.

df['Age'] > 70

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [49]:
df[df["Age"] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [50]:
df[df["Age"] < 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
older_passengers = df[df['Age'] > 70]
older_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [52]:
# get all the female who survived

df[(df['Sex'] == 'female') & df['Survived']]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [53]:
# get all the female who survived

female_surviors_subset = df[(df['Sex'] == 'female') & df['Survived']] [['Name','Age']]
female_surviors_subset.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [54]:
# total number of survivors

print(len(df[df['Survived'] == 1]))

342

In [55]:
survived = len(df[df["Survived"] == 1])
notSurvived = len(df[df['Survived'] == 0])
print(survived + notSurvived)

891

In [56]:
survived/(notSurvived + survived)

0.3838383838383838

In [57]:
female_surviors_subset_loc = df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name','Age']]
female_surviors_subset_loc.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [58]:
df.loc[0, ['Cabin']]

Cabin    NaN
Name: 0, dtype: object

In [59]:
# Number of survivors

print(len(df[df['Survived'] == 1]))

342

# Slicing Rows and Columns

In [60]:
df.loc[0:4, ['Name','Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [61]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [62]:
# I want first 3 rows and first 2 columns

# --> number of index

df.iloc[0:3, 0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [63]:
# First three row and select column by index.

# --> column 1,3

df.iloc[0:3, [1, 3]]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina

In [64]:
df.iloc[0:3, [3, 1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [65]:
df.loc[0:3, ['Name', 'Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1

In [66]:
subset = df[df['Sex'] == 'male']
subset['Age'] = subset['Age'] + 1

print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

C:\Users\fardi\AppData\Local\Temp\ipykernel_27512\3619994415.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Age'] = subset['Age'] + 1

In [67]:
subset = df[df['Sex'] == 'male'].copy()
subset['Age'] += 1

print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [68]:
# iloc --> copy
# loc --> may be view
# df[...] --> may be view

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [70]:
df_by_name = df.set_index('Name')
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
print(df_by_name.loc['Allen, Mr. William Henry'])

PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object

In [72]:
df_by_name = df_by_name.reset_index()
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

# Reindex

In [73]:
sales_jan =pd.DataFrame({
    'Sales': [250, 400, 300]   
}, index=['Store_A','Store_B','Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [74]:
sales_feb =pd.DataFrame({
    'Sales': [260, 320]   
}, index=['Store_A','Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    320

In [75]:
common_index = sales_jan.index

In [76]:
sales_feb_aligned = sales_feb.reindex(common_index)

In [77]:
sales_feb_aligned.head()

         Sales
Store_A  260.0
Store_B    NaN
Store_C  320.0

In [78]:
# fill value in NaN position.
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0)

In [79]:
sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    320

In [80]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     20
Name: Sales, dtype: int64

# For Columns

In [81]:
source_a = pd.DataFrame({
    'Product' : ['Laptop','Table','Phone'],
    'Price' : [1000,500,800],
    'Stock' : [30,50,100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1   Table    500     50
2   Phone    800    100

In [82]:
source_b = pd.DataFrame({
    'Price' : [900,520,810],
    'Product' : ['Laptop','Table','Phone'],
})

source_b

   Price Product
0    900  Laptop
1    520   Table
2    810   Phone

In [83]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    900      0
1   Table    520      0
2   Phone    810      0

# iteration in pandas

In [94]:
df1 = pd.DataFrame({
    'Name' : ['fardin','istyak','nadim'],
    'Age' : [22,26,29],
    'City' : ['Jajpur','Baruan','Brahmabarada']
})

In [95]:
for index, row in df1.iterrows():
    print(row, end='\n\n')

Name    fardin
Age         22
City    Jajpur
Name: 0, dtype: object

Name    istyak
Age         26
City    Baruan
Name: 1, dtype: object

Name           nadim
Age               29
City    Brahmabarada
Name: 2, dtype: object

In [97]:
for index, row in df1.iterrows():
    print(f"{index} : {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0 : fardin lives in Jajpur and is 22 years old.
1 : istyak lives in Baruan and is 26 years old.
2 : nadim lives in Brahmabarada and is 29 years old.

In [98]:
for row in df1.iterrows():
    print(row)

(0, Name    fardin
Age         22
City    Jajpur
Name: 0, dtype: object)
(1, Name    istyak
Age         26
City    Baruan
Name: 1, dtype: object)
(2, Name           nadim
Age               29
City    Brahmabarada
Name: 2, dtype: object)

In [100]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [102]:
df1.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [101]:
for i in df1.index:
    print(i)

0
1
2

In [104]:
for col in df1.columns:
    print(f"Column: {col}")
    print(df1[col].values, end='\n\n')

Column: Name
['fardin' 'istyak' 'nadim']

Column: Age
[22 26 29]

Column: City
['Jajpur' 'Baruan' 'Brahmabarada']

# Condition based Column creation using custom logic

In [105]:
df1.head()

     Name  Age          City
0  fardin   22        Jajpur
1  istyak   26        Baruan
2   nadim   29  Brahmabarada

In [108]:
# if >= 30, senior else young

values = []

for idx, row in df1.iterrows():
    if row['Age'] < 30:
        values.append('young')
    else:
        values.append('senior')

df1['Category'] = values

In [109]:
df1

     Name  Age          City Category
0  fardin   22        Jajpur    young
1  istyak   26        Baruan    young
2   nadim   29  Brahmabarada    young

In [112]:
# again Print the dataframe.
df2 = pd.DataFrame({
    'Name' : ['fardin','istyak','nadim'],
    'Age' : [22,26,29],
    'City' : ['Jajpur','Baruan','Brahmabarada']
})

In [115]:
# vectorized using apply

df2['Categories'] = df2['Age'].apply(lambda age : 'young' if age < 30 else 'senior')

In [116]:
df2

     Name  Age          City Categories
0  fardin   22        Jajpur      young
1  istyak   26        Baruan      young
2   nadim   29  Brahmabarada      young

In [117]:
# apply > itertuples > iterrows.